Increase minimum password requirement to strong
Seravo/seravo-plugin pull request #320
Opened 2020-02-06 10:26 UTC by ottok

This feature was originally introduced in https://github.com/Seravo/seravo-plugin/commit/5218a252d866e1229e44707985b83d940bad3090

Currently the "Update profile" button is disabled if password is weak:
![image](https://user-images.githubusercontent.com/668724/73928375-a9153b00-48db-11ea-84b1-45133e3ec2a9.png)

The button becomes enabled if password is medium:
![image](https://user-images.githubusercontent.com/668724/73928416-ba5e4780-48db-11ea-8af0-fc1351312457.png)

This change lifts the limit and only strong passwords are allowed:
![image](https://user-images.githubusercontent.com/668724/73928447-c813cd00-48db-11ea-99c3-65ca593d7360.png)

To be discussed: is this a good idea? Is medium enough already or not?

2020-02-06 10:34 UTC, simoke commented
Does this cover all kind of users, or just administrators? I prefer strong passwords are forced to use at least for administrative accounts.

2020-02-06 11:09 UTC, nuuttitoivola commented
I personally would like to use strong passwords for all users but I know some site owners might want to have easier passwords available, if they for example have some mass registration thing going on in their site etc. 

Strong passwords for admins is a must as mentioned above. 👍

2020-02-26 11:35 UTC, elguitar commented
There is no reviewer specified. When should this be merged?

2020-02-28 08:48 UTC, ottok commented
> Does this cover all kind of users, or just administrators? I prefer strong passwords are forced to use at least for administrative accounts.

In its current form it would apply to all users.

There is no reviewer assigned, this is for now pending on a decision if we want to do this or not. Mainly we need to figure out are there any concrete drawbacks somewhere.

2020-11-02 21:02 UTC, ottok commented
I've rebased this on latest master. What do you think @elguitar, should we merge this in?

2021-01-18 07:25 UTC, elguitar commented
This is a good change. I think that this should be merged during January-February.

I wonder what's going on with Travis CI

2021-01-18 07:26 UTC, elguitar approved these changes

2021-01-18 09:11 UTC, elguitar requested changes
This should be refactored so that admins have to have strong passwords and the others will remain at `strength > 2`

2021-01-22 13:09 UTC, ottok commented
Actually this change would only apply for the password reset screen. Maybe not worth it after all.

2021-01-25 17:14 UTC, ottok commented
This is actually not feasible to do, as our custom JavaScript only applies to the Reset password screen, not the normal user profile change password screen. Closing as won't implement.

2021-01-25 17:14 UTC, closed without merging