Add a feature for checking site health
Seravo/seravo-plugin pull request #489
Opened 2021-03-01 09:52 UTC by Moppa5

#### What are the main changes in this PR?
The feature adds a postbox to site status page on which users can run site checks. Site checks provides a report about good / pass and potential issues. 

Currently the checks include:
- HTTPS
- Recaptcha
- Deprecated plugins / features (currently wp-palvelu-plugin and https-domain-alias)
- Inactive plugins and themes
- Command `wp-test` status
- PHP error count

The checks are easily extendable as the check-site-health.php class can be extended by adding new logic. Note, translations are still to be done. 

##### Why are we doing this? Any context or related work?
See #66 

#### Screenshots
![Screenshot](https://user-images.githubusercontent.com/16706187/109479587-339a8080-7a83-11eb-9dc8-238f514608d4.png)

![Screenshot(1)](https://user-images.githubusercontent.com/16706187/109479574-309f9000-7a83-11eb-8805-834e67a1e227.png)

2021-03-09 08:06 UTC, elguitar requested changes
Looks good!

I think that it should be more aesthetically pleasing to engage the users to use it.

What do you think, should we add `(Beta)` to the title of this and the redesign on top of this, or should we not merge yet and do improvements?

2021-03-10 08:14 UTC, Moppa5 commented on js/sitestatus.js
> +        jQuery('.object_cache_loading').prop('hidden', true)
Must have been caused by phpcbf "fixing" something.

2021-03-10 08:26 UTC, Moppa5 commented
@elguitar, I think it's best to do improvements before merging. However, I don't have any concrete ideas on how to make it more visually appealing. 

Some questions
- Is the toggle container good or should we have something else?
- Is there something that could be used as a reference? So that features are consistent etc. as well

2021-03-17 13:12 UTC, elguitar requested changes
Minor nagging

2021-03-17 13:34 UTC, Moppa5 commented on modules/check-site-health.php
> +        $php_errors_msg = wp_sprintf(__('%1$s errors on %2$s', 'seravo'), $php_errors, $php_info);
Had this on my mind too about the plurar and singular stuff. I will take a look at that soon.

2021-03-23 13:54 UTC, elguitar approved these changes
This looks good to me :) Added @JoosuaKoskinen for an additional review.

2021-03-23 14:52 UTC, JoosuaKoskinen commented
- [x] Looks good
- [x] Works great
- [x] Feel free to merge

2021-03-23 14:53 UTC, JoosuaKoskinen approved these changes

2021-03-24 11:04 UTC, merged