WIP: Add dashboard widget to show site status
Seravo/seravo-plugin pull request #508
Opened 2021-03-26 09:26 UTC by Moppa5

#### What are the main changes in this PR?
Add a new dashboard widget and show plan details and monthly http requests up to 4 months. It also includes the PHP error count notify. 

##### Why are we doing this? Any context or related work?
See #5 

#### Where should a reviewer start?
What do you think? Should we include something more here, is the layout good and informative etc. ? Any improvements are welcome. 

#### Screenshots
![Screenshot(1)](https://user-images.githubusercontent.com/16706187/112610843-d1386400-8e25-11eb-87bd-369aa0a6588d.png)

2021-03-31 08:14 UTC, elguitar commented
I think it looks wonderful! I am assigning someone outside of dev team to get an alternative opinion.

2021-03-31 08:15 UTC, elguitar commented
Hello @pekkakortelainen! Could you provide us with some thoughts on what could be useful information for this dashboard widget? This would be visible in the wp-admin dashboard front page to the customers.

2021-03-31 10:03 UTC, pekkakortelainen commented
Nice! I think the yellow color will bring a lot more attention to HTTP request tracking. Adding a sentence could help customers in need of a plan upgrade know what to do, e.g. "Contact help@seravo.com to upgrade your [plan](https://seravo.com/plans/)". 

Could we have multiple widgets like this in the future? Could it be useful to have separate widgets for e.g. PHP version (notify if at EOL), disk space? Adding too much information inside one box can lead to dismissing everything. We have these features already under Tools so the data is there.

2021-03-31 11:27 UTC, Moppa5 commented
@pekkakortelainen, I was thinking about adding some text there as well. Some description text and the tip to contact help. 

Theoretically, we can have as many widgets as we want. There are currently some login notifications like for example the PHP error count (currently) as a separate widget, last login notification, some log file related notifications etc. Do you think that we should have for instance the php error count as a separate widget rather than including it on site status? I would keep the php error count on this site status widget for now, but for future there could be a separate widget for showing php error count and the mentioned php end of life? What do you think?

2021-03-31 12:10 UTC, pekkakortelainen commented
Sounds like a good plan! Site status as described above for now and separate widgets in future versions.

2021-03-31 13:38 UTC, JoosuaKoskinen requested changes

2021-03-31 13:38 UTC, JoosuaKoskinen commented on modules/login-notification.php
> +      if ( ! Helpers::is_production() ) {
This should probably be called before any API calls

2021-03-31 13:38 UTC, JoosuaKoskinen commented on modules/login-notification.php
> +        __('This feature is available only on live production sites.', 'seravo');
`__`only returns the translations, use `_e`to print it. Also maybe `return` after this or the code below will be executed anyways.

2021-03-31 13:38 UTC, JoosuaKoskinen commented on modules/login-notification.php
> +           * %1$s contact email link
Multiline `translators` comments will cause warnings on `wp i18n`

2021-03-31 13:38 UTC, JoosuaKoskinen commented on modules/login-notification.php
> +        $total_requests_string = exec("grep -oE 'total_requests\": ([0-9]+),' $report");
Haven't tested this code in practice yet but this looks a bit off. Does it work?

2021-04-01 09:08 UTC, Moppa5 commented on modules/login-notification.php
> +      if ( ! Helpers::is_production() ) {
It surely should. It's fixed now.

2021-04-01 09:13 UTC, JoosuaKoskinen commented on modules/login-notification.php
> +           * %1$s contact email link
`// translators: %1$s contact email link`

2021-04-01 10:12 UTC, JoosuaKoskinen requested changes

2021-04-01 10:12 UTC, JoosuaKoskinen commented on modules/login-notification.php
> +        '; color: #fff; padding: 3px; width: ' . $bar_css . '%; display: inline-block;"><div style="white-space: nowrap;">' .
`width: ' . $bar_css . '%;`

`%` is appended after $bar_css even if it's `auto`

2021-04-01 10:12 UTC, JoosuaKoskinen commented on modules/login-notification.php
> +        if ( $total_requests > $max_requests ) {
`$max_requests` needs to be counted beforehand or the order affects the bar size:

![site-status-requests-1](https://user-images.githubusercontent.com/42264063/113278638-d7798500-92ea-11eb-81b8-22c6c0eed339.png)
![site-status-requests-2](https://user-images.githubusercontent.com/42264063/113278642-d8aab200-92ea-11eb-8aa3-4fbbc98b6147.png)

2021-04-01 10:12 UTC, JoosuaKoskinen commented on modules/login-notification.php
> +          <tbody id="http-reports_table"></tbody>
Is there a reason to close `tbody` here and not on line `337`?

2021-04-01 10:29 UTC, Moppa5 commented on modules/login-notification.php
> +          <tbody id="http-reports_table"></tbody>
Not really sure since this code is ported from JS version. I will take a look at this and possible other excessive lines.

2021-04-01 10:35 UTC, Moppa5 commented on modules/login-notification.php
> +      $site_info = API::get_site_data();
I'm unsure whether this is ok `return _e( $site_info->get_error_message() );` ? Or should there be some other message like "failure fetching plan data" etc. ?

2021-04-01 11:03 UTC, JoosuaKoskinen commented on modules/login-notification.php
> +      $site_info = API::get_site_data();
No variables in `_e`. Probably best to print some failure message and log the real error message in php-error.log

2021-04-01 11:22 UTC, Moppa5 commented on modules/login-notification.php
> +      $site_info = API::get_site_data();
Yeah noticed as well. I put it to `error_log` and made a error message print.

2021-04-01 11:25 UTC, Moppa5 commented on modules/login-notification.php
> +      foreach ( array_reverse($reports) as $report ) {
There will be an error string indicating "The site has no HTTP request statistics yet".

2021-04-01 11:27 UTC, Moppa5 commented on modules/login-notification.php
> +          <tbody id="http-reports_table"></tbody>
Removed the tbody and it didn't affect anything. Presumably it had some functionality on JS side but not on this case

2021-04-01 12:11 UTC, Moppa5 commented on modules/login-notification.php
> +        if ( $total_requests > $max_requests ) {
This should be now fixed on the wip commits.

2021-04-09 08:06 UTC, elguitar approved these changes
I don't have anything to nag about here :D @JoosuaKoskinen thoughts?

2021-04-14 07:35 UTC, JoosuaKoskinen approved these changes
LGTM!

2021-04-14 07:36 UTC, merged