Rewrite database page widgets (Related: 544)
Seravo/seravo-plugin pull request #562
Opened 2021-06-23 11:54 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite 3/5 basic widgets on database page
- Database access
- Adminer link & info
- Database cleanup tools
- Misc changes/additions to helpers

I also added separate `$dryrun_command` as for example `wp-db-cleanup` needs to run `wp-backup` as well whereas with `--dry-run` it must not. This way any dry run command can be separated from the real execution command.

2021-06-23 12:48 UTC, JoosuaKoskinen requested changes

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/lib/ajax/templates/command-runner.php
>      if ( $this->command === null ) {
Could you add these checks (and respond with error):
- If `is_dryrun_enabled()`, `$this->dryrun_command` cant be null
- If `$_GET['dryrun']` is true, `is_dryrun_enabled` must be true (I should have done this)

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/lib/ajax/templates/command-runner.php
> +  public function set_dryrun_command( $command ) {
Maybe `enable_dryrun` and `dryrun` variable should be removed now that we have dryrun_command? Bit unnecessary to write `$handler->set_dryrun_command(...); $handler->enable_dryrun(true);`.

We can just check if dryrun_command is null to see if dryrun whether dryrun is enabled.

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/lib/helpers.php
> +  public static function adminer_link() {
As we talked, this could be just:
```
if ( ! self::is_production() ) {
  return esc_url(str_replace('//', '//adminer.', get_site_url()));
}
return esc_url(get_site_url(null, '.seravo/adminer'));
```

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/lib/postbox/component/template.php
> +      <span aria-hidden="true" class="dashicons dashicons-external" style="line-height: 1.4; padding-left: 3px;"></span> </a>'
Is `style="line-height: 1.4; padding-left: 3px;"` something we could write in common.css instead? Inline CSS should be avoided and is one of the things I would like to get rid of with the refactoring.

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/modules/database.php
> +        sprintf(
In my opinion, this is too verbose. The `init_database_postboxes` is supposed to do basic postbox initialization, titles and stuff but now it's 30% infobox text. The postbox functions are designed to be very compact for the very same reason.

I don't like long lines but I think they could be a better solution. Or maybe something else, I don't know but I would prefer not to have these huge blocks of text and a lot of empty lines just having `)`, `),`, `);` etc.

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/modules/database.php
> +          sprintf(__('<a href="%1$s" target="_BLANK">Adminer</a> is a visual database management tool, which is simpler and safer than its competitor phpMyAdmin.', 'seravo'), 'https://www.adminer.org
Unnecessary usage of `sprintf`. Adds the need for translators -comment which is now 3 useless lines.

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/modules/database.php
> +          sprintf(__('At Seravo it can always be accessed at %1$s.', 'seravo'), '<code>example.com/.seravo/adminer</code>')
Unnecessary sprintf

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/modules/database.php
> +      $base->add_child($button_wrapper);
Each component has wrapper, content and possibly children. This $button_wrapper not has $wrapper and children, no content. Could be just:
```
$button = Template::button_link_with_icon(Helpers::adminer_link(), __('Open Adminer', 'seravo'));
$button->set_wrapper('<p class="adminer_button">', '</p>');
$base->add_child($button);
```

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/modules/database.php
> +      $search_replace->set_build_func(array( __CLASS__, 'database_search_replace_postbox' ));
You added these old functions in to postbox with new design. That's not how they are used and there's a change this causes problems.

If it doesn't cause problems, I guess it's okay as this is to be implemented.

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/modules/database.php
> +      $adminer->set_build_func(array( __CLASS__, 'database_adminer_postbox' ));
Postbox functions used to be named `database_adminer_postbox` etc because that function was the whole postbox. Now the function is only used to build the components for it and is only just a small part of the postbox functionality.

= would prefer `build_adminer_postbox` etc

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/modules/database.php
> +        Template::paragraph(
This is the absolutely correct way to build postboxes, awesome! :+1:

Still dont like the paragraph verbosity, maybe we should think if we can come up with something better?

2021-06-23 12:48 UTC, JoosuaKoskinen commented on src/modules/database.php
> +      $db_info = defined('DB_NAME') ? 'DB_NAME=' . DB_NAME . ' ' : '';
I dont like that this function has so much stuff not related to the postbox initialization. I think max 10 lines for each postbox would be ideal. I know that in some cases it's not achievable but in this case I would do ajax initialization in other function.

2021-06-23 13:04 UTC, Moppa5 commented on src/lib/ajax/templates/command-runner.php
> +      $exec_command = $this->dryrun_command . ' --dry-run';
I was also thinking this before making the PR. I will change the `--dry-run` logic to apply this.

2021-06-23 13:12 UTC, Moppa5 commented on src/lib/ajax/templates/command-runner.php
> +  public function set_dryrun_command( $command ) {
I will add a check for the dryrun_command not being null.

2021-06-23 13:13 UTC, Moppa5 commented on src/lib/ajax/templates/command-runner.php
>      if ( $this->command === null ) {
I will add a check for the dryrun_command being null and error response.

2021-06-23 13:21 UTC, Moppa5 commented on src/lib/ajax/templates/command-runner.php
> +  public function set_dryrun_command( $command ) {
Agreed 👍🏼 . I will modify this.

2021-06-23 13:33 UTC, Moppa5 commented on src/lib/helpers.php
> +  public static function adminer_link() {
I don't remember that we talked about an exact solution and nevertheless the whole code was a bit weird to me. However, I will modify this.

2021-06-23 13:35 UTC, Moppa5 commented on src/lib/postbox/component/template.php
> +      <span aria-hidden="true" class="dashicons dashicons-external" style="line-height: 1.4; padding-left: 3px;"></span> </a>'
Good point! I will investigate and convert them to common.css

2021-06-23 14:06 UTC, Moppa5 commented on src/modules/database.php
> +      $base->add_child($button_wrapper);
I will fix this 👍🏼

2021-06-23 14:07 UTC, Moppa5 commented on src/modules/database.php
> +      $search_replace->set_build_func(array( __CLASS__, 'database_search_replace_postbox' ));
The old widgets are working just fine and I've tested them multiple times. I converted the implementation so that it's easy to start implementing them with the new design right away.

2021-06-23 14:08 UTC, Moppa5 commented on src/modules/database.php
> +      $adminer->set_build_func(array( __CLASS__, 'database_adminer_postbox' ));
I agree. I will change the postbox methods to build and perhaps rephrase them in general.

2021-06-23 14:20 UTC, Moppa5 commented on src/modules/database.php
> +      $db_info = defined('DB_NAME') ? 'DB_NAME=' . DB_NAME . ' ' : '';
Moved these to a helper method to not confuse too much stuff on the main init function.

2021-06-24 08:21 UTC, JoosuaKoskinen approved these changes
Awesome!

2021-06-24 08:24 UTC, merged