Rewrite some security page widgets
Seravo/seravo-plugin pull request #567
Opened 2021-06-30 14:03 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite check passwords and last successful logins postboxes. Also add template for creating HTML tables. Add a description text and link to `wp-login.log` to last successful logins postbox as well. 

##### Why are we doing this? Any context or related work?
Related to #544

2021-06-30 14:21 UTC, Moppa5 commented on src/modules/security.php
> +      $last_logins = new Ajax\LazyLoader('retrieve-logins', 0);
Probably should have / put some cache time for these. I will check and apply these together with possible other change requests.

2021-07-01 16:33 UTC, JoosuaKoskinen requested changes

2021-07-01 16:33 UTC, JoosuaKoskinen commented on src/lib/postbox/component/template.php
> +        $row->add_child(Component::from_raw('<td class="' . $td_class . '">' . $row_element . '</td>'));
The cells used to have tooltips on hover. They need to be added back as most of the strings are cut and that's the only way to see them.

2021-07-01 16:33 UTC, JoosuaKoskinen commented on src/modules/security.php
> +      $last_logins = new Ajax\LazyLoader('retrieve-logins', 0);
Yep, cache for 10 mins should be good, this isn't data that's supposed to be real time.

Also, could you create `Postbox\LazyLoader` and use that instead of `Postbox\Postbox` with `Ajax\LazyLoader`. It hasn't been created just because it hadn't been used yet. It basically just needs to be like the other premade Postboxes but only functions needed is constructor and:
```
public function set_ajax_func( $ajax_func ) {
  $handler = $this->ajax_handlers[$this->id];
  $handler->set_ajax_func($ajax_func);
}
```

2021-07-01 16:33 UTC, JoosuaKoskinen commented on style/common.css
> +  .login_info_table {
I don't think common.css should have postbox specific classes.

In current seravo-plugin-2/master, there's something like that already: https://github.com/Seravo/seravo-plugin/blob/seravo-plugin-2/master/style/common.css#L72

2021-07-01 16:33 UTC, JoosuaKoskinen commented on style/common.css
> +  .login_info_th {
Fix the one above and then you can use `.result-table th {}`. Not good practice to have `_element` like that.

2021-07-01 16:33 UTC, JoosuaKoskinen commented on src/modules/security.php
> +      $passwords->set_requirements(array( Requirements::CAN_BE_PRODUCTION => true ));
I think this Postbox and the one below `CAN_BE_ANY_ENV`, not just in production.

2021-07-01 16:33 UTC, JoosuaKoskinen commented on src/modules/security.php
>        add_action('wp_ajax_seravo_check_passwords', 'seravo_ajax_check_passwords');
Make sure you remove all old code not needed anymore, this could cause issues.

2021-07-01 16:33 UTC, JoosuaKoskinen commented on style/common.css
> +  .seravo-tooltip {
There's replacement for this is master: https://github.com/Seravo/seravo-plugin/blob/seravo-plugin-2/master/style/common.css#L133

2021-07-01 16:33 UTC, JoosuaKoskinen commented on src/modules/security.php
> +        $response->is_success(false);
`is_success(false)` and `set_error` is meant for actually errors. In this there just wasn't anything to show.

2021-07-02 06:46 UTC, Moppa5 commented on src/modules/security.php
> +      $last_logins = new Ajax\LazyLoader('retrieve-logins', 0);
Will do.

2021-07-02 07:18 UTC, Moppa5 commented on src/modules/security.php
> +        $response->is_success(false);
Converted to use set_data and return response normally.

2021-07-02 07:38 UTC, Moppa5 commented on style/common.css
> +  .login_info_table {
Agreed. Will convert.

2021-07-02 07:53 UTC, Moppa5 commented on src/lib/postbox/component/template.php
> +        $row->add_child(Component::from_raw('<td class="' . $td_class . '">' . $row_element . '</td>'));
Absolutely will add them back. The title thing was actually something that I forgot to check afterwards.

2021-07-02 13:20 UTC, JoosuaKoskinen requested changes

2021-07-02 13:20 UTC, JoosuaKoskinen commented on src/lib/postbox/templates/lazy-loader.php
> +   * Constructor for SimpleForm. Will be called on new instance.
Old comment

2021-07-02 13:20 UTC, JoosuaKoskinen commented on src/lib/postbox/templates/lazy-loader.php
> + * command with spinner and showing the output.
Old comment, not executing command

2021-07-02 13:20 UTC, JoosuaKoskinen commented
Feel free to merge after fixing comments

2021-07-02 13:57 UTC, merged