Rewrite some upkeep page postboxes
Seravo/seravo-plugin pull request #572
Opened 2021-07-02 13:10 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite Seravo Plugin update and Change PHP version postboxes. Also, add radio button to templates and remove the old check PHP compatibility as it needs to be re-written so that it doesn't timeout.

2021-07-02 13:14 UTC, JoosuaKoskinen commented
> remove the old check PHP compatibility as it needs to be re-written so that it doesn't timeout
It could be rewritten already as we have to poller merged.

2021-07-05 12:55 UTC, JoosuaKoskinen requested changes
Also, none of the old postboxes worked anymore because JavaScript seems to be broken.

2021-07-05 12:55 UTC, JoosuaKoskinen commented on src/modules/upkeep.php
> +      $update_button = new SimpleCommand('seravo-plugin-update', 'wp-seravo-plugin-update &');
The other postboxes and AJAX handlers use namespace prefix, this one should too.
`Ajax\SimpleCommand`

2021-07-05 12:55 UTC, JoosuaKoskinen commented on src/modules/upkeep.php
> +        $base->add_child(Template::error_paragraph(__('No upstream or current Seravo Plugin version available, please try again later')));
Translate missing domain. Add `'seravo'`.

2021-07-05 12:55 UTC, JoosuaKoskinen commented on src/modules/upkeep.php
> +     * @param mixed $data Data returned by data function.
You are not using $data param

2021-07-05 12:55 UTC, JoosuaKoskinen commented on src/modules/upkeep.php
> +                'output' => Template::error_paragraph(__('The selected PHP version is already in use.', 'seravo'))->to_html(),
Another `Template->to_html`

2021-07-05 12:55 UTC, JoosuaKoskinen commented on src/modules/upkeep.php
> +      $update_button = new SimpleCommand('seravo-plugin-update', 'wp-seravo-plugin-update &');
`wp-seravo-plugin-update` is just ran on background? What happens after the update is done? Is anything outputted to user? I'm not completely sure how this is supposed to work and this is bit hard to test.

2021-07-06 08:13 UTC, JoosuaKoskinen commented
Was the Javascript fixed yet? Still couldn't get it to work.

2021-07-06 08:46 UTC, Moppa5 commented
@JoosuaKoskinen Should be fixed by now. At least I could get the old postboxes working. Are you sure you have pulled the new work?

2021-07-06 10:57 UTC, JoosuaKoskinen approved these changes

2021-07-06 11:03 UTC, merged