Rewrite changes status postbox
Seravo/seravo-plugin pull request #576
Opened 2021-07-06 14:08 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite the changes status postbox on upkeep page. Also add the following things
- New template for date input
- Cleanup this widget's old code but some old upkeep code as well

2021-07-07 06:40 UTC, Moppa5 commented on src/modules/upkeep.php
> +          'seravo'
Most likely should add this as a separate paragraph. Will fix with the possible other changes.

2021-07-07 06:41 UTC, Moppa5 commented on src/modules/upkeep.php
> +      $changes_status->set_title_text(__('Click "run" to see changes', 'seravo'));
"run" => "Run" instead.

2021-07-08 10:13 UTC, JoosuaKoskinen requested changes
Looks good, only one weird comment! :+1

The old upkeep.css also messes with the new output wrapper and 'show more' is a bit miss aligned:
![miss-align](https://user-images.githubusercontent.com/42264063/124905002-3fc4ba80-dfee-11eb-8eb8-970ee9d7e544.png)

2021-07-08 10:13 UTC, JoosuaKoskinen commented on src/lib/postbox/component/template.php
> +   * @return \Seravo\Postbox\Component
Some Rector thing?

2021-07-08 10:20 UTC, Moppa5 commented on src/lib/postbox/component/template.php
> +   * @return \Seravo\Postbox\Component
Probably yes.

2021-07-08 10:30 UTC, JoosuaKoskinen approved these changes

2021-07-08 10:36 UTC, merged