Rewrite site checks postbox
Seravo/seravo-plugin pull request #577
Opened 2021-07-07 13:35 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite Site checks postbox with the new FancyForm. 
- Misc modifications and additions to CSS
- Add method for getting site checks result in HTML
- Remove old excessive code

2021-07-07 14:08 UTC, Moppa5 commented on style/common.css
> +  color: orange !important;
`!important` was added so that no parent div or other can override these specific classes.

2021-07-07 14:09 UTC, Moppa5 commented on style/common.css
> +  margin-top: 2em;
I don't think this was intended. Will check with possible other changes.

2021-07-07 14:10 UTC, Moppa5 commented on style/sitestatus.css
>  }
These styles were added to the `sitestatus.css` because with `overflow-y: scroll;` the tooltips on site checks postbox didn't work properly and were cut. If there's a better way, I'm certainly open to implement.

2021-07-08 12:14 UTC, JoosuaKoskinen requested changes
LGTM! Just check the `em` you found yourself.

2021-07-08 12:14 UTC, JoosuaKoskinen commented on src/modules/sitestatus.php
> +    public static function run_site_checks() {
The work itself is done in separate file, awesome!

2021-07-08 12:14 UTC, JoosuaKoskinen commented on style/sitestatus.css
>  }
I sadly can't come up with a better solution. Let's go with this for now.

2021-07-08 13:23 UTC, Moppa5 commented on style/common.css
> +  color: orange !important;
In this specific case I think these should never be overridden because there's no reason to use these styles if one doesn't need their properties. I wasn't able to find the root cause for the CSS that overrides these but remember something about `#dashboard-widgets` so might be related to seravo-postbox CSS or WordPress CSS in general as well. However, I think these can stay with `!important` as personally I have intended these styles not to be overridden.

2021-07-08 13:36 UTC, merged