Rewrite disk usage postbox
Seravo/seravo-plugin pull request #579
Opened 2021-07-09 13:20 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite the disk usage with the new postbox design and chart handling.
- Add flag variable to LazyLoader AJAX for `<hr>` element
- Change the layout a bit

2021-07-12 06:17 UTC, Moppa5 commented on js/reports-chart.js
> -function generateDatabaseBars(JSONdata) {
This function is still required on database size widget.

2021-07-12 13:11 UTC, JoosuaKoskinen requested changes
- Section `seravo_report_http_requests` now responds with HTTP 400 for some reason.
- The chart is weird. The text overflows and I can't scroll side ways to see the rest:
![disk-usage](https://user-images.githubusercontent.com/42264063/125289473-ef1fcb00-e327-11eb-847b-4b3a2fc9c3d9.png)
- The space-info div is on top of the chart so I can't get chart tooltip hovering on it:
![space-info](https://user-images.githubusercontent.com/42264063/125289910-6f463080-e328-11eb-9294-3cec085f00f3.png)

2021-07-12 13:11 UTC, JoosuaKoskinen commented on js/charts.js
> +// phpcs:disable PEAR.Functions.FunctionCallSignature
Is there a reason to disable PHPCS rule?

2021-07-12 13:11 UTC, JoosuaKoskinen commented on js/charts.js
> +    jQuery('[data-section="disk-usage"]').on('seravoAjaxSuccess', generateDiskDonut);
No need to add `jQuery(document).ready(` for every chart, just use one at the bottom of the file for all charts.

2021-07-12 13:11 UTC, JoosuaKoskinen commented on js/charts.js
> +  new ApexCharts(document.querySelector("#donut_single"), options).render();
The `#donut_single` ID should be something more specific instead. Like `#disk-usage-donut`. Also IDs and classes are always strings, not code, so you should use dashes instead of underscores.

2021-07-12 13:11 UTC, JoosuaKoskinen commented on js/charts.js
> +  var chart = new ApexCharts(document.querySelector("#bars_single"), options);
Another weird ID.

2021-07-12 13:11 UTC, JoosuaKoskinen commented on src/lib/ajax/templates/lazy-loader.php
> +  public $use_hr = true;
See the "This whole setup confuses me" comment.

2021-07-12 13:11 UTC, JoosuaKoskinen commented on src/modules/sitestatus.php
> +      $disk_usage->set_requirements(array( Requirements::CAN_BE_ANY_ENV => true ));
Definitely can't be any env if we are doing SWD API calls.

2021-07-12 13:23 UTC, Moppa5 commented on src/lib/postbox/handler.php
> +          'used'                => __('Used', 'seravo'),
Will add and move them there.

2021-07-12 13:23 UTC, Moppa5 commented on src/modules/sitestatus.php
> +      $disk_usage->set_ajax_func(array( __CLASS__, 'get_disk_usage' ));
Yes, as the disk usage notification on the dashboard widgets uses this cached calculations.

2021-07-12 13:33 UTC, Moppa5 commented on js/charts.js
> +// phpcs:disable PEAR.Functions.FunctionCallSignature
I don't know, it was in the original chart. Will investigate that.

2021-07-12 13:34 UTC, Moppa5 commented on js/charts.js
> +    jQuery('[data-section="disk-usage"]').on('seravoAjaxSuccess', generateDiskDonut);
Noted this when rewriting other widget. Will convert.

2021-07-12 14:22 UTC, Moppa5 commented on src/modules/sitestatus.php
> +      $output = '<div id="donut_single" style="width: 30%; float: left"></div>';
Will investigate and probably convert to better like having the build func separately.

2021-07-12 14:33 UTC, Moppa5 commented on src/lib/ajax/templates/lazy-loader.php
> +  public $use_hr = true;
Partially converted. Will be finalized with the new build func style as well.

2021-07-13 07:39 UTC, Moppa5 commented on js/charts.js
> +  new ApexCharts(document.querySelector("#donut_single"), options).render();
Renamed for the better.

2021-07-13 10:53 UTC, Moppa5 commented on src/lib/postbox/templates/lazy-loader.php
> +    $this->get_ajax_handler($this->id)->use_hr(false);
Damn, first of all this should use the variable `$use_hr`. Secondly it could be converted to use rather `$this->ajax_handlers[$this->id]->use_hr($use_hr)`

2021-07-13 11:15 UTC, JoosuaKoskinen requested changes

2021-07-13 11:15 UTC, JoosuaKoskinen commented on js/charts.js
> +function generateDatabaseBars(JSONdata) {
Could you rename this function name and parameter to snake_case

2021-07-13 11:15 UTC, JoosuaKoskinen commented on js/charts.js
> +function generateDiskDonut(event, response) {
snake_case

2021-07-13 11:15 UTC, JoosuaKoskinen commented on js/charts.js
> +  var chart = new ApexCharts(document.querySelector("#bars-single"), options);
This ID still could be more specific

2021-07-13 11:15 UTC, JoosuaKoskinen commented on src/lib/postbox/toolpage.php
> +          'used'                => __('Used', 'seravo'),
Why so much space?

2021-07-13 11:15 UTC, JoosuaKoskinen commented on src/lib/ajax/templates/lazy-loader.php
> +  private $use_hr = true;
I'm still very much not a fan of having flags for random elements but lets go with this for now.

2021-07-13 11:18 UTC, Moppa5 commented on src/lib/postbox/toolpage.php
> +          'used'                => __('Used', 'seravo'),
Probably some rector / phpcs case.

2021-07-13 11:44 UTC, merged