Rewrite cache status postbox
Seravo/seravo-plugin pull request #582
Opened 2021-07-14 14:51 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite the cache status postbox with the new design.
- Object cache nag with the new nag bar implementation
- Charts to the chart.js file
- Cache tests wrapper

2021-07-14 14:58 UTC, Moppa5 commented on style/common.css
> +}
This could potentially be excessive and implemented in plain HTML when wanted. However, I liked the way that I could use for example `<p class="success bold"></p>` optionally if wanted.

2021-07-14 15:16 UTC, JoosuaKoskinen requested changes

2021-07-14 15:16 UTC, JoosuaKoskinen commented on src/lib/ajax/templates/simple-form.php
> +  private $hideable = false;
I thought you meant Javascript side autohide when you asked me if this is needed. If this isn't used, please remove it.

2021-07-14 15:16 UTC, JoosuaKoskinen commented on style/common.css
> +}
I don't mind that.

2021-07-14 15:16 UTC, JoosuaKoskinen commented on src/modules/sitestatus.php
> +     * Inits AJAX handlers
Comment missing `@param`'s

2021-07-14 15:16 UTC, JoosuaKoskinen commented on src/modules/sitestatus.php
> +     * @param Postbox $postbox Postbox The box.
Classes in comments should have namespace prefixed. We do have multiple classes with the same name.

2021-07-14 15:16 UTC, JoosuaKoskinen commented on src/modules/sitestatus.php
> +      $object_cache->set_spinner_text(__('Enabling object cache...', 'seravo'));
Spinner text isn't supported in nag-bar. Just looks buggy:
![object-cache](https://user-images.githubusercontent.com/42264063/125646023-2b2156bc-011a-4fe9-bae0-d98054ca539f.gif)

2021-07-15 06:35 UTC, Moppa5 commented on src/lib/ajax/templates/simple-form.php
> +  private $hideable = false;
I will remove it then.

2021-07-15 08:25 UTC, JoosuaKoskinen requested changes
Review done now

2021-07-15 08:36 UTC, Moppa5 commented on src/modules/sitestatus.php
> +     * @param Postbox $postbox Postbox The box.
Good point! Will try to pay more attention to this so that they are consistent with the prefixes and namespaces on the given context.

2021-07-16 09:10 UTC, JoosuaKoskinen requested changes
Really good PR overall! :tada: Everything done as intended.

One small change request and couple of optional requests.
Feel free to merge after handling them.

2021-07-16 09:10 UTC, JoosuaKoskinen commented on src/modules/sitestatus.php
> +      $cache_status->set_ajax_func(array( __CLASS__, 'get_cache_hit_rate' ));
Maybe this should be cached?

2021-07-16 09:10 UTC, JoosuaKoskinen commented on js/charts.js
> +  console.log(response)
Left from debug

2021-07-16 09:10 UTC, JoosuaKoskinen commented on src/modules/sitestatus.php
> +      $bypasses = Template::paragraph(
Could bypasses be in same format as expired/evicted keys?
Current format: `There are X bypasses`
Requested format: `Bypasses: X (*tooltip explaining bypasses*)`

2021-07-16 09:22 UTC, Moppa5 commented on js/charts.js
> +  console.log(response)
Oups, I thought that I removed it, perhaps I didn't commit that 😄

2021-07-16 09:23 UTC, Moppa5 commented on src/modules/sitestatus.php
> +      $cache_status->set_ajax_func(array( __CLASS__, 'get_cache_hit_rate' ));
Sure! I will put 10 minutes for it.

2021-07-16 09:25 UTC, Moppa5 commented on src/modules/sitestatus.php
> +      $bypasses = Template::paragraph(
Good idea! That would be more consistent and the tool-tip explaining about bypasses would be very nice.

2021-07-16 09:49 UTC, merged