Rewrite speed test postbox
Seravo/seravo-plugin pull request #583
Opened 2021-07-15 14:30 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite the speed test postbox and functionality with the new design / Simpleform.
- Add quick toggle for clearing the location / page input
- Add `speedtest.js` for executing the speed test related AJAX requests etc.
- Move chart creation to the common `chart.js`

2021-07-16 09:40 UTC, JoosuaKoskinen requested changes

2021-07-16 09:40 UTC, JoosuaKoskinen commented on js/speedtest.js
> +// phpcs:disable PEAR.Functions.FunctionCallSignature
Is this actually needed?

2021-07-16 09:40 UTC, JoosuaKoskinen commented on js/speedtest.js
> +jQuery(document).ready(function ($) {
Don't place everything in `jQuery(document).ready()`. Only put this part in it:
```
// Check if there is a 'speed_test_target' key in the url
let searchParams = new URLSearchParams(window.location.search);
if (searchParams.has('speed_test_target')) {
  run_speed_test();
}

$('#speed-test-button').click(run_speed_test);
$('#clear-url').click(
  function() {
    $("#speed-test-url").val('');
});
  ```
  
  Functions don't need to be defined there. Just useless indents.

2021-07-16 09:43 UTC, Moppa5 commented on js/speedtest.js
> +// phpcs:disable PEAR.Functions.FunctionCallSignature
It is as without there are some phpcs nags that phpcbf can't fix. I can re-check this again when working with the other request.

2021-07-16 09:44 UTC, Moppa5 commented on js/speedtest.js
> +jQuery(document).ready(function ($) {
Sure. This is most likely a habit that comes from the page specific js files where nearly everything is placed inside the `jQuery(document).ready...` However, I understand the point and will "fix".

2021-07-16 09:51 UTC, Moppa5 commented on js/speedtest.js
> +// phpcs:disable PEAR.Functions.FunctionCallSignature
After moving the functions out of the `jQuery` part it seems that the issues are fixed. Will remove.

2021-07-19 11:22 UTC, JoosuaKoskinen approved these changes
LGTM & FFTM

2021-07-19 11:23 UTC, merged