Rewrite creating pages
Seravo/seravo-plugin pull request #586
Opened 2021-07-19 09:55 UTC by JoosuaKoskinen

#### What are the main changes in this PR?
- Move pages under `src/module/pages/` to seperate them from real modules.
- Composer autoload pages.
- Make pages be instances of `\Seravo\Postbox\Toolpage` instead of creating an Toolpage instance separately.
- Add requirements/access management for Toolpages.
- Make Toolpages take care of submenu registering instead of need for `toolbox.php`. 
- Fix invalid script registering and unify them.

This is going to create conflicts, needs to be merged carefully.

2021-07-19 10:35 UTC, Moppa5 reviewed
Looking great overall 🎉! It seems that Database size widget is not working as the disk bars charts are not loading and spinners are spinning forever. However, #585 should take care of rewriting the widget and as we discussed it would be nice to merge these new widgets before this massive PR.

I will probably re-review this when everything is fully ready. However, I didn't come across any major flaws that we should take care of. The new `pages/` structure is much better, and to me it seems that the pages are getting simpler (there's no excessive loading and stuff done). Great job!

2021-07-19 10:45 UTC, JoosuaKoskinen commented
> It seems that Database size widget is not working as the disk bars charts are not loading and spinners are spinning forever

That was because I forgot to enable charts for the page (`$this->enable_charts();`). Should be fixed now. 

> I will probably re-review this when everything is fully ready

Yep, the PR is probably going to change a bit as we merge old PR's first.

2021-07-20 06:31 UTC, Moppa5 requested changes
Great work! Consider those two changes / questions and after that I think you can feel free to merge this 🎉

2021-07-20 06:31 UTC, Moppa5 commented on src/lib/postbox/toolpage.php
>   */
Should we update the class comment in to something like "Toolpage is a base class for building pages that provide a simple way to handle a postbox screen --". For some reason the comment feels a little outdated regarding this new abstract design.

2021-07-20 06:31 UTC, Moppa5 commented on seravo-plugin.php
> +    require_once SERAVO_PLUGIN_SRC . 'modules/check-site-health.php';
Site Health module is not an old AJAX file nor has it anything to do with AJAX?

2021-07-20 07:52 UTC, JoosuaKoskinen commented on src/lib/postbox/toolpage.php
>   */
Comment changed.

2021-07-20 07:52 UTC, JoosuaKoskinen commented on seravo-plugin.php
> +    require_once SERAVO_PLUGIN_SRC . 'modules/check-site-health.php';
Added a comment for it.

2021-07-20 08:29 UTC, merged