Rewrite cruftfiles postbox
Seravo/seravo-plugin pull request #588
Opened 2021-07-21 13:46 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite the cruftfiles postbox with the new design.

- Autoloadable CruftRemover PHP class
- Common JS file for all cruft remover widgets
- Some css style changes & additions
- Move cruft files listing under `seravo-container` so that it overflows rather than consuming the whole page

#### Manual testing steps?
One can use for example the following bash script for generating some mock cruft files when testing.
```
#!/bin/bash
for ((index = 0; index <32; index++))
do
touch /data/wordpress/$index.sql
done
```

2021-07-26 09:58 UTC, JoosuaKoskinen requested changes
The code is good! Just a couple of design notes: 

- The button looks different than other buttons in the plugin
![cruftfile1](https://user-images.githubusercontent.com/42264063/126962925-031b5b60-4efc-4fa5-8cb0-ae82c3494ad5.png)
- The postbox is really tall, could be much shorter as there's the scrollbar
- There's a weird line at bottom right corner:
![cruftfile2](https://user-images.githubusercontent.com/42264063/126964524-53ea1aaf-e265-4f72-a27a-db31020f1544.png)
- Maybe use WordPress popup like this instead of `confirm`?
![cruftfile3](https://user-images.githubusercontent.com/42264063/126964659-f772b57b-af60-448e-a78c-0c4690ad927c.png)

2021-07-26 09:58 UTC, JoosuaKoskinen commented on js/cruftremover.js
> + * @param {array} remove_list List of the content to remove.
\@Param comments, awesome!

2021-07-26 09:58 UTC, JoosuaKoskinen commented on src/modules/pages/security.php
> +   * @param $base The base of the postbox to add elements.
The `$base` is missing type.

2021-07-26 09:58 UTC, JoosuaKoskinen commented on style/cruftremover.css
> +.cruft-delete-button {
Why doesn't it use `.button`?

2021-07-26 09:58 UTC, JoosuaKoskinen commented on src/modules/pages/security.php
> +use Seravo\Ajax\AjaxHandler;
Please make it `\Seravo\...`

2021-07-26 10:32 UTC, Moppa5 commented on style/cruftremover.css
> +.cruft-delete-button {
Good point. Maybe too much reverse engineering and didn't even think about that. I will try to fit the consistent button as other widgets have as well :)

2021-07-27 08:10 UTC, Moppa5 commented on js/cruftremover.js
> +        } */
Should remove these...

2021-07-27 08:23 UTC, JoosuaKoskinen requested changes
- The "The selected files have..." is on bit weird place, almost touching the table. Is the text even needed? We could show the "Not removed" text on failure but on success customer will see the entry disappear from the table.
![cruftfiles](https://user-images.githubusercontent.com/42264063/127120976-aa38806d-8811-4a1b-9b4e-6514a4312dc5.png)
- The weird line from previous review is still there

LGTM otherwise

2021-07-27 08:59 UTC, merged