Rewrite cruft plugins postbox
Seravo/seravo-plugin pull request #594
Opened 2021-07-23 12:44 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite the cruft plugins postbox with the new design.
- Remove and move old AJAX code to CruftRemover class
- Remove old CSS from `cruftremover.css`
- Move some functions to `cruftremover.js`
- Add spinner and proper error messages if removing a plugin(s) fails

You can easily generate cruft plugins for example with this bash script
```
#!/bin/bash
wp plugin install w3-total-cache
wp plugin install wp-super-cache
wp plugin install better-wp-security
wp plugin install wordfence
wp plugin install jetpack
wp plugin install backup
wp plugin install wp-cerber
wp plugin install all-in-one-wp-migration
```

#### Where should a reviewer start?
This PR is depending on #588 so it should be merged first.

2021-07-26 10:34 UTC, JoosuaKoskinen requested changes
This still reminds me a lot of the old design, with cruft*.php files and cruft*.js just combined together. I would like to see the JS be completely common code, it shouldn't need to even know what type of cruft remover it is. The postbox could just have `data-cruft-type=plugin` etc and JS would send it to one common AJAX handler which would then decide what function should be called to remove them:
```
public static function remove_cruft() {
  $cruft_type = isset($_POST['cruft-type']) ? $_POST['cruft-type'] : '';
  $cruft = isset($_POST['cruft']) ? $_POST['cruft'] : '';
  if ( $cruft_type === 'plugin' ) {
    return CruftRemover::remove_cruft_plugins($cruft);
  } else if ( $cruft_type === 'file' ) {
    return CruftRemover::remove_cruft_files($cruft);
  } else if ( $cruft_type === 'theme' ) {
    return CruftRemover::remove_cruft_themes($cruft);
  } else {
    return // *ajax error response*
  }
}
``` 

- The spinner is not very aligned:
![spinner](https://user-images.githubusercontent.com/42264063/126972590-dc4e8378-9c09-4f1a-acb2-7d398bbc58f1.gif)
- The cruftfiles and cruftplugins output are very different. Could you remove the text still shown after removing plugins? And the `<hr>` at the end.
![cruftplugins2](https://user-images.githubusercontent.com/42264063/126972902-0369f386-4360-4bf8-b79d-860a1ab29d85.png)

2021-07-26 10:34 UTC, JoosuaKoskinen commented on js/cruftremover.js
> +function cruft_plugins(event, response) {
Okay this is not a general cruft remover thing at all but a huge postbox specific function to take care of almost everything. Is there a reason this cant be done with one common function?

2021-07-26 10:34 UTC, JoosuaKoskinen commented on src/lib/cruftremover.php
> +        foreach ( $cruft_found as $key => $cruft_dir ) {
Looks like you broke the indentation

2021-07-26 10:34 UTC, JoosuaKoskinen commented on js/cruftremover.js
> +function sort_data_array(dataArray) {
Could the data just be sorted on backend?

2021-07-26 10:34 UTC, JoosuaKoskinen commented on src/modules/pages/security.php
> +    $base->add_child(Component::from_raw('<div id="cruft-plugins-status"></div>'));
This makes no sense

2021-07-26 10:34 UTC, JoosuaKoskinen commented on src/modules/pages/security.php
> +        'data' => $call_section,
What is this call_section and why is just passed back without using it?

2021-07-27 08:12 UTC, Moppa5 commented on js/cruftremover.js
> +function cruft_plugins(event, response) {
I will investigate and work with the more common way.

2021-07-27 08:22 UTC, Moppa5 commented on src/modules/pages/security.php
> +    $base->add_child(Component::from_raw('<div id="cruft-plugins-status"></div>'));
True, added to a wrong function :D. However, when modifying in to more general style there should be something like `div class="cruft-status">`

2021-07-27 14:53 UTC, Moppa5 commented on src/modules/pages/security.php
> +        'data' => $call_section,
The call section is removed for now, need to work out something else for it as well.

2021-07-28 12:10 UTC, Moppa5 commented
Waiting now for us to re-implement the `cruftremover.js` with a better design.

2021-08-17 19:40 UTC, Moppa5 commented
Closing this as #613 takes care of the cruft rewrite.

2021-08-17 19:40 UTC, closed without merging