Rewrite Seravo Updates postbox
Seravo/seravo-plugin pull request #597
Opened 2021-07-29 11:59 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite the Seravo Updates postbox with the new design.

- Rename the HTML elements
- Remove plenty of excessive CSS
- Own build func for the settings

2021-08-04 14:13 UTC, JoosuaKoskinen requested changes

2021-08-04 14:13 UTC, JoosuaKoskinen commented on src/modules/pages/upkeep.php
> +  public static function build_seravo_updates_settings_form( $data ) {
This function is a huge block of text. Could some of these use template like Template::button etc? Or maybe create some more if needed? For example instead of:
```
$updates_checked = (isset($data['seravo_updates_on']) && $data['seravo_updates_on'] === true) ? 'checked="checked"' : '';
$updates_form->add_child(Component::from_raw('<input id="seravo-updates" name="seravo-updates" type="checkbox" ' . $updates_checked . '>' . __('Seravo updates enabled', 'seravo')));
```
could have:
```
$updates_form->add_child(Template::checkbox('seravo-updates', $data['seravo_updates_on']));
```
Isset() kind of stuff should be done in data function.

This function feels a lot like it's just the same HTML but parsed with Component::from_raw()

2021-08-04 14:13 UTC, JoosuaKoskinen commented on src/modules/pages/upkeep.php
> +    $updates_form->add_child(Component::from_raw('<hr class="seravo-updates-hr">'));
Is that class actually even needed?

2021-08-04 14:13 UTC, JoosuaKoskinen commented on style/upkeep.css
> -#dashboard_right_now .seravo-updates-postbox,
Custom CSS file :( If it's needed, it's needed. Could rename as updates.css.

2021-08-05 06:08 UTC, Moppa5 commented on style/upkeep.css
> -#dashboard_right_now .seravo-updates-postbox,
Well that would be the case if it was the only one using the CSS on upkeep page.

2021-08-05 06:12 UTC, Moppa5 commented on js/upkeep.js
> +        insertEmail();
WIll be modified.

2021-08-05 07:58 UTC, Moppa5 commented on js/upkeep.js
> -// phpcs:disable PEAR.Functions.FunctionCallSignature
- Changed `upkeep.js` => `updates.js`
- Use `is_email_valid(email)`
- Refactor code, remove `$`, apply snake_case etc.

2021-08-09 07:56 UTC, JoosuaKoskinen requested changes
Just a few small requests

2021-08-09 07:56 UTC, JoosuaKoskinen commented on src/modules/pages/upkeep.php
> +    wp_enqueue_script('updates-js', SERAVO_PLUGIN_URL . 'js/updates.js', array( 'jquery' ), Helpers::seravo_plugin_version());
Not sure if removing the `seravo` prefix is a good idea. The `updates-js` sounds like something that could conflict with other scripts on some site.

2021-08-09 07:56 UTC, JoosuaKoskinen commented on src/modules/pages/upkeep.php
>      $site_info = self::seravo_admin_get_site_info();
Why not just use `API` class instead of that useless seravo_admin_get_site_info?

2021-08-09 07:56 UTC, JoosuaKoskinen commented on src/modules/pages/upkeep.php
> +    $base->add_child(self::build_seravo_updates_settings_form($data));
This separate function for building the form seems quite useless. Confusing how text for the first section is here but the checkbox and rest of sections are in different function. Could `build_seravo_updates_form` just be removed and appended here?

2021-08-09 08:03 UTC, Moppa5 commented on src/modules/pages/upkeep.php
> +    wp_enqueue_script('updates-js', SERAVO_PLUGIN_URL . 'js/updates.js', array( 'jquery' ), Helpers::seravo_plugin_version());
Well I change the `screenshots-js` to `seravo-screenshots-js` as well so there will be no conflicts and we don't forget that either.

2021-08-09 08:10 UTC, Moppa5 commented on src/modules/pages/upkeep.php
>      $site_info = self::seravo_admin_get_site_info();
Removed it and the method + all occurrences.

2021-08-10 10:30 UTC, JoosuaKoskinen commented on src/modules/pages/upkeep.php
> +    wp_enqueue_script('updates-js', SERAVO_PLUGIN_URL . 'js/updates.js', array( 'jquery' ), Helpers::seravo_plugin_version());
Screenshots hasn't been refactored yet, you can change it if you want to

2021-08-10 11:23 UTC, JoosuaKoskinen requested changes
Feel free to merge after resolving the one comment!

2021-08-10 11:23 UTC, JoosuaKoskinen commented on src/modules/pages/upkeep.php
>      if ( isset($site_info['notification_webhooks'][0]['url']) &&
I think this will error if `$site_info['notification_webhooks'][0]` doesn't exists. Are you sure the API always returns that?

2021-08-10 12:55 UTC, merged