Rewrite the dashboard widgets
Seravo/seravo-plugin pull request #600
Opened 2021-08-03 13:57 UTC by Moppa5

#### What are the main changes in this PR?
Rewrite the dashboard widgets module. AJAX is not included on dashboard widgets, but it can most likely be added later on if wanted. 

- Use the new postbox design for creating the widgets
- Some minor refactoring and renaming.

#### Where should a reviewer start?
#596 has already renamed the class and most likely will cause some conflicts thus it would be nice to review it first.

2021-08-04 06:21 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
This should be removed when #596 is merged as it should be fully autoloadable then.

2021-08-04 06:35 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +        }
I just noticed that there should be the limit part on the dashboard widget so that the HTTP requests statistics is shown for the past 4-5 month or so. Will fix now.

2021-08-04 06:49 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +        }
Limit is now 5 past months and it's managed by constant value for the clarity.

2021-08-06 09:12 UTC, Moppa5 commented on rector.php
> -
As discussed these were removed on newer Rector version. There were some Rector nags regarding some WP_CLI and Security page, but I didn't apply them on this PR.

2021-08-09 09:44 UTC, JoosuaKoskinen requested changes

2021-08-09 09:44 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +    $disk_usage_url = '<a href="' . get_option('siteurl') . '/wp-admin/tools.php?page=site_status_page#disk_usage_heading" target="_blank">' .
I don't think #disk_usage_heading or #cruftfiles_tool are valid

2021-08-09 09:44 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
>        $php_version_change_url = '<a href="' . get_option('siteurl') . '/wp-admin/tools.php?page=upkeep_page#change_php_version" target="_blank">' .
Another link with invalid id, please check all the links

2021-08-09 09:44 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +        Template::text(__('Disk space in your plan: ') . '<b>' . $data['disk_space'] . '</b>'),
Avoid spaces at the end of translation strings, they are annoying when translating

2021-08-09 09:44 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +    self::render_widgets();
Kind of misleading function name, this doesn't render anything, only registers the widget

2021-08-09 09:44 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +          Requirements::CAN_BE_STAGING => true,
Not sure if the site plan disk limit is available in staging, make sure it is

2021-08-09 09:51 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +          Requirements::CAN_BE_STAGING => true,
Well the only reason was that dashboard widgets most likely don't add any value in development. Can add though.

2021-08-09 10:10 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +    self::render_widgets();
Don't agree as it calls` wp_add_dashboard_widget` and then calls `_build` which renders those. Basically in my opinion the function registers and renders those widgets.

2021-08-09 11:16 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +    $disk_usage_url = '<a href="' . get_option('siteurl') . '/wp-admin/tools.php?page=site_status_page#disk_usage_heading" target="_blank">' .
They are now fixed and replaced with the postbox ids.

2021-08-09 11:18 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +        Template::text(__('Disk space in your plan: ') . '<b>' . $data['disk_space'] . '</b>'),
Should be ok now.

2021-08-09 11:18 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +          Requirements::CAN_BE_STAGING => true,
Yeah didn't work on staging. I fixed Sitestatus disk usage widget as well.

2021-08-09 14:29 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +      $base->add_child(Template::section_title(__('Old PHP Version', 'seravo')));
@JoosuaKoskinen, I was thinking that we could use `Compatibility::get_php_version()` here as well, but it's private method. I think the method might be something that could be used throughout in Seravo Plugin to safely check the version. What do you think?

2021-08-10 12:41 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +      $base->add_child(Template::section_title(__('Old PHP Version', 'seravo')));
IMO would be best if the method was moved to `\Seravo\Helpers` and made public there. Feel free to do so.

2021-08-11 06:25 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +      $base->add_child(Template::section_title(__('Old PHP Version', 'seravo')));
The method is now moved to the Helpers class.

2021-08-11 06:26 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +use enshrined\svgSanitize\Helper;
Don't know what this is...

2021-08-11 06:27 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +use enshrined\svgSanitize\Helper;
Don't know how this ended up here but will remove immediately.

2021-08-16 11:33 UTC, JoosuaKoskinen requested changes

2021-08-16 11:33 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +      \error_log('Plan details error');
This is bit weird, first prints WP error message and then "Plan details error"
```
[16-Aug-2021 11:21:10 UTC] API call failed. Aborting. The error has been logged.
[16-Aug-2021 11:21:10 UTC] Plan details error
```

2021-08-16 11:33 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +        \preg_match('/(\d+)/', $total_requests_string, $total_requests_match);
Make sure `preg_match` returns `1`, otherwise it has failed

2021-08-16 11:33 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +   * Fetch the full disk space usage, backups and logs excluded. The main logic from sitestatus-ajax.php
"The main logic from sitestatus-ajax.php" can be removed?

2021-08-16 11:33 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +  const PHP_EOL_VERSION = '7.3';
Current EOL version is `7.2` + alert is not shown using the version specified in PHP_EOL_VERSION

2021-08-16 11:35 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +      \error_log('Plan details error');
This has been left when I debugged something. Will remove.

2021-08-16 11:35 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +          Requirements::CAN_BE_STAGING => true,
Why doesn't it? The developer should be told if using PHP <=7.2 so they change to a newer one and the site doesn't break once moved to production

2021-08-16 11:39 UTC, JoosuaKoskinen commented on src/modules/dashboard-widgets.php
> +    self::render_widgets();
> it calls wp_add_dashboard_widget and then calls _build

It does not call `_build`. It only registers the widget.

2021-08-16 12:18 UTC, Moppa5 commented on src/modules/dashboard-widgets.php
> +    self::render_widgets();
For the sake of consistency we can go with `register_widgets`.

2021-08-16 12:22 UTC, JoosuaKoskinen approved these changes
Feel free to merge

2021-08-16 12:29 UTC, merged